<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone Number</name>
   <tag></tag>
   <elementGuidId>002cff97-b345-42e3-89bf-4577b10cdf3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@ng-reflect-name = 'labelPhone']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#FfJSq</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='FfJSq']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7330685e-755e-4729-a5ec-e0cbb2c6d8f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>labelPhone</value>
      <webElementGuid>0b6adc99-1dca-4b21-b683-c0585dd63ddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FfJSq</value>
      <webElementGuid>6d662af1-eb7a-44b3-988c-f9bb9e0c282d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FfJSq</value>
      <webElementGuid>776e8988-20b8-43ee-b389-73026df3159f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>47275fd0-b66e-4e37-a5de-8333c35a5ad8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FfJSq&quot;)</value>
      <webElementGuid>e9c5d20b-808f-4fab-b3a8-1789f59b2fea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='FfJSq']</value>
      <webElementGuid>e0ac682d-a2d6-4cc1-b0b2-d2e001d677ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>80f20080-a038-4fc2-8357-759e27841abe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'FfJSq' and @name = 'FfJSq']</value>
      <webElementGuid>eed908e1-2911-4c54-9ffc-8d7f4eac7c62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
