<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email</name>
   <tag></tag>
   <elementGuidId>0daaba41-81f6-46c7-b167-035b2253e400</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@ng-reflect-name = 'labelEmail']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#NVlsC</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NVlsC']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e23c568e-afe9-46cb-bb81-bb9579d9d557</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>labelEmail</value>
      <webElementGuid>12f69699-ff1e-410d-b3df-4635110cad91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NVlsC</value>
      <webElementGuid>435c1fdf-64dd-4732-a552-845367e84d38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NVlsC</value>
      <webElementGuid>750b9592-9c01-4209-a009-7c951c38252d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>92cfc11c-1888-493e-9c3c-f23afade092f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NVlsC&quot;)</value>
      <webElementGuid>ec7fadd9-a404-4464-9e00-026d69dc4702</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NVlsC']</value>
      <webElementGuid>ccb99f59-a9c6-4dde-b406-d52406a9563b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/rpa1-field/div/input</value>
      <webElementGuid>a85d430c-fc39-469c-9b27-1fbdbd1f4fb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'NVlsC' and @name = 'NVlsC']</value>
      <webElementGuid>b61f10cb-e5ef-4981-9ebe-6eba7cdcd7c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
