<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First Name</name>
   <tag></tag>
   <elementGuidId>d288779b-8c7f-4606-9c68-de7a52ed9b07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@ng-reflect-name = 'labelFirstName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dlxVb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dlxVb']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d55db62f-5e44-486a-9d07-fd432b72c488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>labelFirstName</value>
      <webElementGuid>cbdbbd31-2ff2-4454-875f-7f472b27a92a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dlxVb</value>
      <webElementGuid>b2263483-d5b2-4c7d-b951-fdc6ac35ebdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dlxVb</value>
      <webElementGuid>2b6b475c-c54d-488a-bdc6-925d4e1e5ecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>84729bd8-728d-4f8d-ba6f-4bc5b37a5483</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dlxVb&quot;)</value>
      <webElementGuid>b88b4efd-d8ae-4fd6-9cdc-da8cdca88bfb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dlxVb']</value>
      <webElementGuid>7cf7284a-4205-4d89-ac41-dcdaa3484905</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/rpa1-field/div/input</value>
      <webElementGuid>72b2b0f9-f3f2-46d3-856a-8d18668627ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dlxVb' and @name = 'dlxVb']</value>
      <webElementGuid>2b2626a1-565e-4c67-bf9d-a39b33536448</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
