<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Role in Company</name>
   <tag></tag>
   <elementGuidId>c9f4777c-768e-4788-aea7-39d543ccf31b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@ng-reflect-name = 'labelRole']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#yzTEa</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='yzTEa']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d462f487-ef42-4220-a56d-cc29581f6737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>labelRole</value>
      <webElementGuid>76723708-e418-4f58-86c1-3c7c0af3ac0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>yzTEa</value>
      <webElementGuid>e9e128f9-e1bf-4ea5-b2dc-fa6df6ae18f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>yzTEa</value>
      <webElementGuid>3b917450-46a4-4c94-a0e7-498bb6895820</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>9b2039c7-602b-4a0a-b45d-bb2c13967197</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yzTEa&quot;)</value>
      <webElementGuid>3e72985f-b03f-43c1-84bd-0fa1197151b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='yzTEa']</value>
      <webElementGuid>fa9a8402-ebc1-4799-8c2e-d75eeb9bb989</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/rpa1-field/div/input</value>
      <webElementGuid>81dcc18e-8e42-4673-af76-e7064bc320e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'yzTEa' and @name = 'yzTEa']</value>
      <webElementGuid>db60e97b-13d7-49b1-87fc-6f2f33a83802</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
