<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Last Name</name>
   <tag></tag>
   <elementGuidId>ddc1c205-86cf-4da8-9ded-890abd6d6f9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@ng-reflect-name = 'labelLastName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PsNkN</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>&#xd;
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6b10f52d-5d18-4f69-b869-274ec79ae893</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>labelLastName</value>
      <webElementGuid>8d4ec13d-c92b-4470-9dfc-6949e31f7210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PsNkN</value>
      <webElementGuid>dc57340f-c615-4583-8aff-9500a5c570de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PsNkN</value>
      <webElementGuid>157f0c19-9e05-4449-bf38-1ff54ff742ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-invalid ng-touched</value>
      <webElementGuid>571cb72f-6010-41b2-9617-0a06672f35a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PsNkN&quot;)</value>
      <webElementGuid>e54d7737-cc9d-4483-9411-9e57c5d92f81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PsNkN']</value>
      <webElementGuid>3bf3456a-ef71-4dd6-add7-84587deeeab1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/rpa1-field/div/input</value>
      <webElementGuid>a789f9b0-cb2b-467e-aaa7-46b1ae847293</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PsNkN' and @name = 'PsNkN']</value>
      <webElementGuid>2a86de57-1d1e-4e4b-8e5a-4a8e6046d5ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
