<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Company Name</name>
   <tag></tag>
   <elementGuidId>09b786c0-2431-4cb2-a82c-9fb95199a0f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@ng-reflect-name = 'labelCompanyName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#KSXOP</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='KSXOP']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ffb4c25a-6614-46a9-9135-a92440128afe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>labelCompanyName</value>
      <webElementGuid>3569c301-65aa-4bd4-9bd2-b42e3074134c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>KSXOP</value>
      <webElementGuid>888f6ef8-3e11-4e68-97c5-a7eaab2da69d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>KSXOP</value>
      <webElementGuid>0b4d8c5f-10c7-4c1c-802a-3e11a7971c90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>aef6b470-5051-4e91-8453-ffff2eea5468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;KSXOP&quot;)</value>
      <webElementGuid>a5161add-47b5-4aca-aa11-88fa3eba3863</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='KSXOP']</value>
      <webElementGuid>3a540bc4-e927-4ee0-9790-cf0115658a36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/rpa1-field/div/input</value>
      <webElementGuid>202bd926-d2d5-4571-9746-595045cea3f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'KSXOP' and @name = 'KSXOP']</value>
      <webElementGuid>c43c4c8e-6c46-4d3a-8444-8d093f520b26</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
