<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address</name>
   <tag></tag>
   <elementGuidId>57a1a389-7a6d-4403-9e5e-058b9f7884c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@ng-reflect-name = 'labelAddress']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#KiVtC</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='KiVtC']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8bb95a0f-475a-4e23-bb8c-fe504ed95f98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>labelAddress</value>
      <webElementGuid>df41764d-352f-46b5-944f-a8db8f613dad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>KiVtC</value>
      <webElementGuid>c2db2e7b-a01a-48c4-badf-56f29e330e74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>KiVtC</value>
      <webElementGuid>cecfd9a5-386d-4075-bedb-10669a5a5cac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>7b55468a-8e3e-4510-8dc9-6e3fb3ff6e89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;KiVtC&quot;)</value>
      <webElementGuid>d9b1c1bb-b84c-45c3-9542-130738fb45f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='KiVtC']</value>
      <webElementGuid>aad5c633-f9ee-4fd3-985b-272b4236c69a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/rpa1-field/div/input</value>
      <webElementGuid>ffb96184-ba1b-45b0-9aa6-d5d81fe6e20a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'KiVtC' and @name = 'KiVtC']</value>
      <webElementGuid>a9bfb33c-9d6c-4f1c-b484-30de788669fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
